### ISSUE TITLE
Mean Function

### ISSUE THREAD

**Issue by RajeshPatkar** [RajeshPatkarInstitute/RpISE-Statgine#1]
Please Implement Mean Function.

**Comment by SravanSai10** [comment]
def mean(sortedList):
    total = 0
    for i in range(len(sortedList)):
        total += i

    return float(total/len(sortedList))

**Comment by SravanSai10** [comment]
def mean(sortedList):
    total = 0
    for i in sortedList:
        total += i

    return float(total/len(sortedList))

**Comment by SravanSai10** [comment]
def mean(sortedList):

    total = 0
    for i in sortedList:

        total += i

    return float(total/len(sortedList))

**Comment by RajeshPatkar** [comment]
Hello SarvanSai please post your code [HERE](https://github.com/RajeshPatkarInstitute/RpISE-Statgine/blob/master/Core/Mean.py)

**Comment by RajeshPatkar** [comment]
Is it necessary for the list to be sorted to find out Mean?

**Comment by RajeshPatkar** [comment]
Hello Sravan I have checked your code. I recommend that you skip the sort as it a costly operation and is not mandatory for you algorithm.

**Comment by RajeshPatkar** [comment]
You have used data as list. You have listVar variable as well as data as local variable. Can we just do with just one variable? For instance what if we make listVar as parameter?

**Comment by SravanSai10** [comment]
Hello Sir! I removed the sort() operation and used one variable listVar as suggested.
